"""Add new columns to Bridge model

Revision ID: 90c6269997e5
Revises: 171288f352aa
Create Date: 2024-01-30 10:31:57.188041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c6269997e5'
down_revision = '171288f352aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facility', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('crossing', sa.String(length=100), nullable=True))

    with op.batch_alter_table('product_item_association', schema=None) as batch_op:
        batch_op.drop_constraint('product_item_association_item_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item_association', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_item_association_item_id_key', ['item_id'])

    with op.batch_alter_table('bridge', schema=None) as batch_op:
        batch_op.drop_column('crossing')
        batch_op.drop_column('facility')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
